### your site title here

title: 小朋友的會計程式之路

sass: 
    style: compressed


# Tracker
analytics: UA-83979019-1


exclude:
- README.md

include: 
- _pages

gems: [jekyll-paginate]
paginate: 5
paginate_path: blog/page:num/