### your site title here

title: A CPA's Tech Note

sass: 
    style: compressed


# Tracker
analytics: UA-83979019-1


exclude:
- README.md

include: 
- _pages

gems: [jekyll-paginate]
paginate: 5

# Permalinks
permalink: pretty


url: https://noworneverev.github.io
baseurl: 

