### your site title here

title: Accoding

sass: 
    style: compressed


# Tracker
analytics: UA-106614437-1


exclude:
- README.md

include: 
- _pages

plugins: [jekyll-paginate]
paginate: 5

# Permalinks
permalink: pretty


url: https://noworneverev.github.io
baseurl: 

port: 5001